language: python
python:
  - "3.9"
install:
  - gem install chef-utils -v 16.6.14
  - gem install mdl
  - pip install -r requirements.txt
script:
  # speller.yandex.net doesn't work anymore
  # - rozental --reorder_vocabulary .
  - mdl --style=.mdlrc.rb .
